# Generated by Django 4.1 on 2022-09-07 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "first_image",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "second_image",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userType",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "ADMIN"), (2, "CUSTOMER")], default=2
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orderStatus",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "CREATED"),
                            (2, "PENDING"),
                            (3, "DELIVERED"),
                            (4, "RETURNED"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk_api.profile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk_api.product",
                    ),
                ),
            ],
        ),
    ]
